<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__btn-submit</name>
   <tag></tag>
   <elementGuidId>1da51b11-a09b-4190-9258-c849a42c1580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af5b0dfa-a55b-43e4-93e4-53d8e45c18b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>be2d94e7-36e8-49f3-89b4-23d6fd68f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d749b9fd-15b4-48ab-a248-23b3ad67afb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>0988a0b9-8c79-489b-b8b8-2704224009a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Ambil dari Master
                                        </value>
      <webElementGuid>0633620e-fcce-46e1-9043-4e2d1e472915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-submit&quot;)</value>
      <webElementGuid>386ac5b5-218f-4d39-81b9-e0a1fdf91abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-submit']</value>
      <webElementGuid>faa7a635-fbb4-4af9-90f0-b92fc7bb98bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-produk']/div[10]/button</value>
      <webElementGuid>4da2d344-fe51-4f0f-9eb1-a36983c01d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::button[1]</value>
      <webElementGuid>b7e1b4f4-7e2f-4605-93cb-3415bf937d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>25337d99-bb21-4c03-8f95-bdfb94dff2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btn-submit' and (text() = '
                                             Ambil dari Master
                                        ' or . = '
                                             Ambil dari Master
                                        ')]</value>
      <webElementGuid>1655ee4e-526c-478b-a7bf-de4c2643af93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
