<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih dari Master Produk_pilih_master</name>
   <tag></tag>
   <elementGuidId>11386e4b-3e6a-4f78-9048-89a87d2a6ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pilih_master']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pilih_master</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d732f82-ab9f-4ced-bf25-0b7ef377c6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93f950d9-9d90-4e48-bc18-96f5cc90e448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilih_master</value>
      <webElementGuid>246c60e2-993e-4d92-abf6-d2d380bc765b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pilih_master</value>
      <webElementGuid>317b38c7-6072-4f34-b20b-fd8caf3686b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Master Produk --43UN7000PTA (Stok Master: 32)CS-PN9WKJ (Stok Master: 41)CWD-5601 (Stok Master: 41)GC1020 (Stok Master: 42)KAS-1609 (Stok Master: 45)LG001 (Stok Master: 10)MRJ-1808 (Stok Master: 21)PFL1053 (Stok Master: 35)RT29K5032S8 (Stok Master: 42)SRS-XB23 (Stok Master: 28)</value>
      <webElementGuid>b3cd7531-bfe6-4c02-b4e6-201e27a463fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilih_master&quot;)</value>
      <webElementGuid>b38f72a4-bec7-440c-9768-dcd0bbe8af0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pilih_master']</value>
      <webElementGuid>3c519e4c-a1f2-4f60-b7d7-ffa1040abe9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_master']/div[2]/select</value>
      <webElementGuid>0cde8f52-583e-40a7-8f15-3970d753d93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih dari Master Produk'])[1]/following::select[1]</value>
      <webElementGuid>add159df-16fd-4454-9533-6637dd8733d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Produk yang Sudah Ada'])[1]/preceding::select[1]</value>
      <webElementGuid>e189d737-34bf-433c-b189-7c0e80ad998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dde03e3e-b255-40ce-af8b-ab7a6ddce699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pilih_master' and @name = 'pilih_master' and (text() = '-- Pilih Master Produk --43UN7000PTA (Stok Master: 32)CS-PN9WKJ (Stok Master: 41)CWD-5601 (Stok Master: 41)GC1020 (Stok Master: 42)KAS-1609 (Stok Master: 45)LG001 (Stok Master: 10)MRJ-1808 (Stok Master: 21)PFL1053 (Stok Master: 35)RT29K5032S8 (Stok Master: 42)SRS-XB23 (Stok Master: 28)' or . = '-- Pilih Master Produk --43UN7000PTA (Stok Master: 32)CS-PN9WKJ (Stok Master: 41)CWD-5601 (Stok Master: 41)GC1020 (Stok Master: 42)KAS-1609 (Stok Master: 45)LG001 (Stok Master: 10)MRJ-1808 (Stok Master: 21)PFL1053 (Stok Master: 35)RT29K5032S8 (Stok Master: 42)SRS-XB23 (Stok Master: 28)')]</value>
      <webElementGuid>80ebbc0d-65ec-4b98-9ae9-98c5696d2c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
