<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn save</name>
   <tag></tag>
   <elementGuidId>a7ed02b4-d13b-4a51-8a8d-0be8f85ed129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btn-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6c9036e-64e9-4d05-813c-fac477fc3198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-text</value>
      <webElementGuid>b251927e-639e-4bda-a6f1-9916bd5684be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan Barang Baru</value>
      <webElementGuid>c3817cef-5c80-4e59-9560-bcdea65730b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-text&quot;)</value>
      <webElementGuid>dcba362b-4fcf-497f-9064-3f6e0340cdb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btn-text']</value>
      <webElementGuid>0fc846f3-cc13-4592-befe-b0984fde8e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-submit']/span</value>
      <webElementGuid>4712922f-830e-4233-b98f-6d71efe8ec69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok ini adalah stok master barang.'])[1]/following::span[1]</value>
      <webElementGuid>2a4db8ad-8ade-41c0-9b51-eef03f20a0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi:'])[1]/following::span[2]</value>
      <webElementGuid>c284ee8f-3a7f-406c-9bdf-36849c57d834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan Barang Baru']/parent::*</value>
      <webElementGuid>85931b59-2c64-4fb8-8faf-359ee33b3ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button/span</value>
      <webElementGuid>445abae8-2d40-4676-b41c-ed88ae0805eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btn-text' and (text() = 'Simpan Barang Baru' or . = 'Simpan Barang Baru')]</value>
      <webElementGuid>6b8514bf-214b-4cbf-9152-cf079103dbe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
