<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inputNamaBarang</name>
   <tag></tag>
   <elementGuidId>edfbc991-3a0e-4aaf-b539-b10e390efbfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNamaBarang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputNamaBarang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f68e8777-8fec-4b29-9c02-ca382c37aee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4193e416-be19-411d-b704-ba27f8d3e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2195ff91-1d2d-4b93-bedf-a852d57b5fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNamaBarang</value>
      <webElementGuid>46d09b5e-6c68-4633-a7c8-683b81b2e56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_produk</value>
      <webElementGuid>62c6fd12-dbe2-49bc-b29b-430b0c7fd9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Produk</value>
      <webElementGuid>6554210b-8de6-4387-8702-79f8b94b6414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNamaBarang&quot;)</value>
      <webElementGuid>8a5cc80e-376e-4f3f-a7de-3be3433ba5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNamaBarang']</value>
      <webElementGuid>45bbee50-6e8d-4e83-b172-70dcf75b0e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-produk']/div[4]/input</value>
      <webElementGuid>04a094e7-8e55-46ce-8986-ef438a474404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b6c7775b-381b-4275-b71b-d6e233903bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNamaBarang' and @name = 'nama_produk' and @placeholder = 'Masukkan Nama Produk']</value>
      <webElementGuid>9dbd55d2-5e86-42e0-a7b5-b9b592e8aec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
