<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__btn btn-sm btn-primary</name>
   <tag></tag>
   <elementGuidId>863aa8f0-8a72-4174-b57c-da4afab2cb0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/section/div/div/div/div/div[2]/div/div[2]/table/tbody/tr[5]/td[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) > td.green > div.d-flex.gap-2 > a.btn.btn-sm.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17c8e68b-8db8-4242-ba30-1ebf6be5e9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/users/5/edit</value>
      <webElementGuid>50dc3c54-a9e3-442c-b85d-97049fb93e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>09150a06-b381-4293-a624-1f5aa4afe7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>9f34f370-ebf0-4023-a3ed-4dcf2c5e1b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/section[@class=&quot;section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns&quot;]/div[@class=&quot;datatable-container&quot;]/table[@class=&quot;table datatable datatable-table&quot;]/tbody[1]/tr[5]/td[@class=&quot;green&quot;]/div[@class=&quot;d-flex gap-2&quot;]/a[@class=&quot;btn btn-sm btn-primary&quot;]</value>
      <webElementGuid>e6db4344-3b4b-4d7b-bd3e-484d4dadd865</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/section/div/div/div/div/div[2]/div/div[2]/table/tbody/tr[5]/td[5]/div/a</value>
      <webElementGuid>27e0cd96-5786-4a3e-a6cb-1dcc98c30443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[5]</value>
      <webElementGuid>a2fa7d72-6c5e-48a8-ba06-7cde514b1382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='**********'])[5]/following::a[1]</value>
      <webElementGuid>63b9044e-43fb-489c-88da-260ee3ebcf15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='supri@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>86e78805-17ce-4874-aff3-342ecbd701b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspend'])[5]/preceding::a[1]</value>
      <webElementGuid>95b095db-b9c1-41b3-9267-8ca238d1f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 5 of 5 entries'])[1]/preceding::a[1]</value>
      <webElementGuid>85ebd102-4392-43ca-a707-2e2985fc7025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/users/5/edit']</value>
      <webElementGuid>ebbf135b-f05c-4e66-aec3-b4b6f01ae526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/div/a</value>
      <webElementGuid>e501b863-12ff-4231-b50a-58f5d0ccec63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/users/5/edit' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>55336894-c52d-444a-9ece-2546e91738a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
