<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Produk yang Sudah Ada_pilih_existing</name>
   <tag></tag>
   <elementGuidId>5ff1ad2f-fc6a-4bc1-bf72-1dacc48c9826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pilih_existing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pilih_existing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd659cb4-3377-4e7e-a6d3-f913506730ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>30154d1f-0451-4c9d-a6e9-de6cf6c66196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilih_existing</value>
      <webElementGuid>2dcdd90c-850d-4367-b6e5-11d258da9260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pilih_existing</value>
      <webElementGuid>721109fe-b14c-4262-aa9d-63898ca2311e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Produk Existing --SRS-XB23 (Stok Toko: 3, Master: 15)</value>
      <webElementGuid>ec9f0440-ef3a-4eb5-bb6b-c4729df66e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilih_existing&quot;)</value>
      <webElementGuid>e6f9b954-2a06-421f-84a9-c911be47fa8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pilih_existing']</value>
      <webElementGuid>b82f6da6-82e2-45bc-afb6-7819e483ec50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_existing']/div[2]/select</value>
      <webElementGuid>b377b090-fe8d-4ba9-88d4-b338562d24fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Produk yang Sudah Ada'])[1]/following::select[1]</value>
      <webElementGuid>7f1b5bc8-7c7e-4dd5-acca-9bc99cf2a57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>afd0339e-005c-409e-89f0-c52df1adf4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>b15c1b08-0f74-4796-a347-d12011ea539b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pilih_existing' and @name = 'pilih_existing' and (text() = '-- Pilih Produk Existing --SRS-XB23 (Stok Toko: 3, Master: 15)' or . = '-- Pilih Produk Existing --SRS-XB23 (Stok Toko: 3, Master: 15)')]</value>
      <webElementGuid>ac056706-70ac-4dfe-ac71-1e80e00f16be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
