<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stok tersedia 14_produk0jumlah</name>
   <tag></tag>
   <elementGuidId>214bb7c7-c881-4150-91ec-72003ee3926d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='produk[0][jumlah]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;produk[0][jumlah]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de9643f6-7d5b-4b22-a844-71c73f389a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4053cf27-53e6-4e7d-8c79-36702f2d7b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jumlah</value>
      <webElementGuid>08744d41-7f56-41e8-8220-1d83c5da65bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>produk[0][jumlah]</value>
      <webElementGuid>1f1a73c0-fbdf-4db5-b51f-44101c476723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>efd631e3-8bec-4960-97ca-6c62a5218947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>36d695ac-8613-41be-91b6-c6c93981af71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;produk-container&quot;)/tr[@class=&quot;produk-item&quot;]/td[4]/input[@class=&quot;form-control jumlah&quot;]</value>
      <webElementGuid>10b6c42e-eb2d-46f2-8fa7-3a680ee6b09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='produk[0][jumlah]']</value>
      <webElementGuid>595518f2-13b7-412e-9487-5f5c9452deaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='produk-container']/tr/td[4]/input</value>
      <webElementGuid>e8dfc7b9-6ed0-422b-8e87-5d8f28f57b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>7e6bc4e4-0d36-487f-9a02-6adaad474596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'produk[0][jumlah]']</value>
      <webElementGuid>ad4477e4-b204-4ec1-a120-194a494ff168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
