<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stok tersedia 10_produk1jumlah</name>
   <tag></tag>
   <elementGuidId>29b8311f-db8d-4c5b-952b-f1b70ee83d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='produk[1][jumlah]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;produk[1][jumlah]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15ab1239-41ce-4b63-ac53-006b00293e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>955fd635-6a1e-4cf5-88de-13259bc6d183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jumlah</value>
      <webElementGuid>96c6fda3-ecf7-41d7-af83-dc19facbdba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>produk[1][jumlah]</value>
      <webElementGuid>1561861a-efc5-4e3e-81ee-6377db35b553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3117f23-4b50-46f6-a7f9-fd1b89861591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>877c215a-2aa1-452e-a1e4-57cb99d7d562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;produk-container&quot;)/tr[@class=&quot;produk-item&quot;]/td[4]/input[@class=&quot;form-control jumlah&quot;]</value>
      <webElementGuid>2f95d622-83a6-403a-a376-9f42b7b785a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='produk[1][jumlah]']</value>
      <webElementGuid>e2bb0789-9979-4220-b420-c29bb71f44fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='produk-container']/tr[2]/td[4]/input</value>
      <webElementGuid>2098b120-3b1c-4927-915f-0d29a4340c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>0467fbd6-f695-409a-8b8a-ac24cfb77945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'produk[1][jumlah]']</value>
      <webElementGuid>28e7b932-c753-471a-929a-58a02f5daa91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
