<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inputNamaBarang</name>
   <tag></tag>
   <elementGuidId>3008576d-c56b-4ab3-afd4-2e9ecfaff292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNamaBarang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputNamaBarang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5012f466-81c6-4336-8dd7-ef6936f1a16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2a6c621-3ed7-4aff-a022-b608a78f135d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e103435-0a4e-44fa-88f0-6a8dd1f00527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNamaBarang</value>
      <webElementGuid>f7aa58a4-8784-4ab6-89bf-39676152c416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_produk</value>
      <webElementGuid>6c76751c-64a0-4199-a100-e134e2036bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Produk</value>
      <webElementGuid>d0d4bc9d-4357-4f92-b2a3-1c63bd26fb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LG001</value>
      <webElementGuid>9bf5135a-3baf-4e2c-819c-3ed224e19128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNamaBarang&quot;)</value>
      <webElementGuid>949cf1d5-01d8-46a1-bea1-252828210835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNamaBarang']</value>
      <webElementGuid>62a9bbff-84d8-4361-84ec-505bc637db65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-edit-produk']/div/input</value>
      <webElementGuid>0df63d8a-ccfe-474b-9bfd-3153ad3e4d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b4e916cf-f050-43b5-bb3d-8c7b4e222619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNamaBarang' and @name = 'nama_produk' and @placeholder = 'Masukkan Nama Produk']</value>
      <webElementGuid>998056be-dbf8-4d12-a030-4fe144dad015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
